=== Khalid-Lamachi/Application-de-gestion-de-taches-avec-XML-Base-de--donnees/XML/taches.dtd
<!ELEMENT taches (tache+)>
<!ELEMENT tache (titre, description, etat, dateCreation)>
<!ATTLIST tache id ID #REQUIRED priorite (basse | moyenne | haute) #REQUIRED>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT etat (#PCDATA)>
<!ELEMENT dateCreation (#PCDATA)>

=== Khalid-Lamachi/Application-de-gestion-de-taches-avec-XML-Base-de--donnees/XML/taches.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE taches SYSTEM "taches.dtd">
<taches>
    <tache id="T1" priorite="haute">
        <titre>Tache 1</titre>
        <description>description 1</description>
        <etat>En cours</etat>
        <dateCreation>2026-05-25</dateCreation>
    </tache>
    
    <tache id="T2" priorite="moyenne">
        <titre>Tache 2</titre>
        <description>Description 2</description>
        <etat>Terminée</etat>
        <dateCreation>2026-05-24</dateCreation>
    </tache>
</taches>
